In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.options.display.max_columns=50
sns.set(style="darkgrid",rc={"axes.facecolor":"#CAF1DE"})

In [2]:
df=pd.read_csv("DATASET ASSIGNMENT.csv")
print(df)

    Unnamed: 0             Unnamed: 1 REPORTED CASES           Unnamed: 3  \
0          NaN                    NaN            NaN                  NaN
1          NaN                    NaN   Totals Cases  Cases under Inquiry
2        S/No.  CASE/CRIME INCIDENCES              1                    2
3          NaN              HOMICIDES            NaN                  NaN
4            1   Death  (by shooting)            190                  117
..         ...                    ...            ...                  ...
122         98            UWA Statute            648                  112
123         99   Local Government Act              4                    2
124        100         All other Acts            821                  345
125        NaN  Sub Total(Other Laws)          3,006                  749
126        NaN            GRAND TOTAL        238,746               90,763

           Unnamed: 4            Unnamed: 5                 PERFOMANCE  \
0                 NaN                   NaN                        NaN
1    Not Detected/NPW  Cases taken to court  Cases submitted toDPP/RSA
2                   3                     4                          5
3                 NaN                   NaN                        NaN
4                  29                    44                         74
..                ...                   ...                        ...
122                89                   447                        485
123                 1                     1                          1
124               189                   287                        430
125               620                 1,637                      1,885
126            74,948                73,035                    101,116

                 Unnamed: 7             Unnamed: 8       Unnamed: 9  \
0                       NaN                    NaN              NaN
1    Cases with convictions  Cases with Acquittals  Cases Dismissed
2                         6                      7                8
3                       NaN                    NaN              NaN
4                         3                      1                1
..                      ...                    ...              ...
122                     269                      8               26
123                       -                      -                -
124                     173                      7               19
125                     991                     24              127
126                  22,263                  1,248           11,121

                Unnamed: 10 PERSONS TAKEN TO COURT  Unnamed: 12   Unnamed: 13  \
0                       NaN        ACCUSED CHARGED          NaN           NaN
1    Cases pending in Court             Male Adult  Male Juven.  Female Adult
2                         9                     10          NaN           NaN
3                       NaN                    NaN          NaN           NaN
4                        39                     85            -             -
..                      ...                    ...          ...           ...
122                     144                    609            7            17
123                       1                      1            -             -
124                      93                    641           12            76
125                     500                  3,592           49           416
126                  38,411                 79,083        2,355         5,988

       Unnamed: 14        Unnamed: 15  Unnamed: 16   Unnamed: 17  \
0              NaN  ACCUSED CONVICTED          NaN           NaN
1    Female Juven.         Male Adult  Male Juven.  Female Adult
2              NaN                 11          NaN           NaN
3              NaN                NaN          NaN           NaN
4                -                  4            -             -
..             ...                ...          ...           ...
122              -                377            -            11
123              -                  -            -             -
124              -                323            8            44
125            138              2,183           54           314
126            596             24,716          812         1,944

       Unnamed: 18 Unnamed: 19 Unnamed: 20     Unnamed: 21  \
0              NaN         NaN         NaN             NaN
1    Female Juven.   Acquitted  Discharged  Awaiting Trial
2              NaN          12          13              14
3              NaN         NaN         NaN             NaN
4                -           1           1              79
..             ...         ...         ...             ...
122              -          10          42             193
123              -           -           -               1
124              -           1          56             297
125             19          29         280           1,316
126            223       1,666      12,518          46,143

    SENTENCES IMPOSED BY COURTS  Unnamed: 23   Unnamed: 24    Unnamed: 25  \
0                  IMPRISONMENT          NaN           NaN            NaN
1                    Male Adult  Male Juven.  Female Adult  Female Juven.
2                           NaN          NaN           NaN             15
3                           NaN          NaN           NaN            NaN
4                             4            -             -              -
..                          ...          ...           ...            ...
122                         249            3             4              -
123                           -            -             -              -
124                         121            2             3              -
125                       1,291            7            18              -
126                      17,138          274           823             31

    Unnamed: 26 Unnamed: 27           Unnamed: 28 Unnamed: 29 Unnamed: 30  \
0           NaN         NaN                   NaN         NaN         NaN
1         Death       Fined  Probation Bound Over     CAUTION  COMM. WORK
2            16          17                    18          19          20
3           NaN         NaN                   NaN         NaN         NaN
4             -           -                     -           -           -
..          ...         ...                   ...         ...         ...
122           -         107                     -          15          10
123           -           -                     -           -           -
124           -         120                    21          41          60
125           -         810                    21         292         123
126           -       1,967                    83       2,976       4,373

                 Unnamed: 31       Unnamed: 32  Unnamed: 33   Unnamed: 34  \
0                        NaN  VICTIMS OF CRIME          NaN           NaN
1    Fines  Awarded (UgShs.)        Male Adult  Male Juven.  Female Adult
2                         21               NaN          NaN           NaN
3                        NaN               NaN          NaN           NaN
4                          -               197            4            17
..                       ...               ...          ...           ...
122              172,222,000               608            -             8
123                        -                 4            -             -
124               69,060,000               710           10            62
125              518,202,000             2,676           10           115
126            1,270,978,007           143,880       10,772        60,648

       Unnamed: 35             Unnamed: 36     Unnamed: 37
0              NaN  VALUE PROPERTY(UGSHS.)             NaN
1    Female Juven.                    Lost       Recovered
2               22                      23              24
3              NaN                     NaN             NaN
4                -              11,500,000               -
..             ...                     ...             ...
122              -              26,000,000      26,000,000
123              -                       -               -
124              9             241,790,000         440,000
125              9             274,390,000      26,440,000
126         24,184         495,067,703,285  60,589,926,327

[127 rows x 38 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   95 non-null     object
 1   Unnamed: 1                   125 non-null    object
 2   REPORTED CASES               125 non-null    object
 3   Unnamed: 3                   125 non-null    object
 4   Unnamed: 4                   125 non-null    object
 5   Unnamed: 5                   125 non-null    object
 6   PERFOMANCE                   125 non-null    object
 7   Unnamed: 7                   125 non-null    object
 8   Unnamed: 8                   125 non-null    object
 9   Unnamed: 9                   125 non-null    object
 10  Unnamed: 10                  125 non-null    object
 11  PERSONS TAKEN TO COURT       126 non-null    object
 12  Unnamed: 12                  124 non-null    object
 13  Unnamed: 13                  124 non-null    object
 14  Unnamed: 14                  124 non-null    object
 15  Unnamed: 15                  126 non-null    object
 16  Unnamed: 16                  124 non-null    object
 17  Unnamed: 17                  124 non-null    object
 18  Unnamed: 18                  124 non-null    object
 19  Unnamed: 19                  109 non-null    object
 20  Unnamed: 20                  109 non-null    object
 21  Unnamed: 21                  109 non-null    object
 22  SENTENCES IMPOSED BY COURTS  109 non-null    object
 23  Unnamed: 23                  108 non-null    object
 24  Unnamed: 24                  108 non-null    object
 25  Unnamed: 25                  109 non-null    object
 26  Unnamed: 26                  109 non-null    object
 27  Unnamed: 27                  109 non-null    object
 28  Unnamed: 28                  109 non-null    object
 29  Unnamed: 29                  109 non-null    object
 30  Unnamed: 30                  109 non-null    object
 31  Unnamed: 31                  109 non-null    object
 32  Unnamed: 32                  100 non-null    object
 33  Unnamed: 33                  107 non-null    object
 34  Unnamed: 34                  99 non-null     object
 35  Unnamed: 35                  108 non-null    object
 36  Unnamed: 36                  110 non-null    object
 37  Unnamed: 37                  109 non-null    object
dtypes: object(38)
memory usage: 37.8+ KB

In [4]:
df.columns
df

,Unnamed: 0,Unnamed: 1,REPORTED CASES,Unnamed: 3,Unnamed: 4,Unnamed: 5,PERFOMANCE,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,PERSONS TAKEN TO COURT,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,SENTENCES IMPOSED BY COURTS,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ACCUSED CHARGED,NaN,NaN,NaN,ACCUSED CONVICTED,NaN,NaN,NaN,NaN,NaN,NaN,IMPRISONMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VICTIMS OF CRIME,NaN,NaN,NaN,VALUE PROPERTY(UGSHS.),NaN
1,NaN,NaN,Totals Cases,Cases under Inquiry,Not Detected/NPW,Cases taken to court,Cases submitted toDPP/RSA,Cases with convictions,Cases with Acquittals,Cases Dismissed,Cases pending in Court,Male Adult,Male Juven.,Female Adult,Female Juven.,Male Adult,Male Juven.,Female Adult,Female Juven.,Acquitted,Discharged,Awaiting Trial,Male Adult,Male Juven.,Female Adult,Female Juven.,Death,Fined,Probation Bound Over,CAUTION,COMM. WORK,Fines Awarded (UgShs.),Male Adult,Male Juven.,Female Adult,Female Juven.,Lost,Recovered
2,S/No.,CASE/CRIME INCIDENCES,1,2,3,4,5,6,7,8,9,10,NaN,NaN,NaN,11,NaN,NaN,NaN,12,13,14,NaN,NaN,NaN,15,16,17,18,19,20,21,NaN,NaN,NaN,22,23,24
3,NaN,HOMICIDES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Death (by shooting),190,117,29,44,74,3,1,1,39,85,-,-,-,4,-,-,-,1,1,79,4,-,-,-,-,-,-,-,-,-,197,4,17,-,"11,500,000",-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,98,UWA Statute,648,112,89,447,485,269,8,26,144,609,7,17,-,377,-,11,-,10,42,193,249,3,4,-,-,107,-,15,10,"172,222,000",608,-,8,-,"26,000,000","26,000,000"
123,99,Local Government Act,4,2,1,1,1,-,-,-,1,1,-,-,-,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,-,4,-,-,-,-,-
124,100,All other Acts,821,345,189,287,430,173,7,19,93,641,12,76,-,323,8,44,-,1,56,297,121,2,3,-,-,120,21,41,60,"69,060,000",710,10,62,9,"241,790,000","440,000"
125,NaN,Sub Total(Other Laws),"3,006",749,620,"1,637","1,885",991,24,127,500,"3,592",49,416,138,"2,183",54,314,19,29,280,"1,316","1,291",7,18,-,-,810,21,292,123,"518,202,000","2,676",10,115,9,"274,390,000","26,440,000"
126,NaN,GRAND TOTAL,"238,746","90,763","74,948","73,035","101,116","22,263","1,248","11,121","38,411","79,083","2,355","5,988",596,"24,716",812,"1,944",223,"1,666","12,518","46,143","17,138",274,823,31,-,"1,967",83,"2,976","4,373","1,270,978,007","143,880","10,772","60,648","24,184","495,067,703,285","60,589,926,327"

In [5]:
df.isnull().sum().sort_values(ascending=False)

Unnamed: 0                     32
Unnamed: 34                    28
Unnamed: 32                    27
Unnamed: 33                    20
Unnamed: 35                    19
Unnamed: 23                    19
Unnamed: 24                    19
Unnamed: 26                    18
SENTENCES IMPOSED BY COURTS    18
Unnamed: 25                    18
Unnamed: 29                    18
Unnamed: 27                    18
Unnamed: 28                    18
Unnamed: 20                    18
Unnamed: 30                    18
Unnamed: 31                    18
Unnamed: 21                    18
Unnamed: 19                    18
Unnamed: 37                    18
Unnamed: 36                    17
Unnamed: 14                     3
Unnamed: 12                     3
Unnamed: 13                     3
Unnamed: 18                     3
Unnamed: 16                     3
Unnamed: 17                     3
Unnamed: 10                     2
Unnamed: 1                      2
Unnamed: 8                      2
Unnamed: 7                      2
PERFOMANCE                      2
Unnamed: 5                      2
Unnamed: 4                      2
Unnamed: 3                      2
REPORTED CASES                  2
Unnamed: 9                      2
Unnamed: 15                     1
PERSONS TAKEN TO COURT          1
dtype: int64

In [7]:
df.duplicated().sum()

0

In [9]:
df1=df.dropna()
df1

,Unnamed: 0,Unnamed: 1,REPORTED CASES,Unnamed: 3,Unnamed: 4,Unnamed: 5,PERFOMANCE,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,PERSONS TAKEN TO COURT,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,SENTENCES IMPOSED BY COURTS,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
4,1,Death (by shooting),190,117,29,44,74,3,1,1,39,85,-,-,-,4,-,-,-,1,1,79,4,-,-,-,-,-,-,-,-,-,197,4,17,-,"11,500,000",-
5,2,Death (by mob action),636,431,109,96,176,2,-,1,93,194,-,10,-,3,-,-,-,-,3,198,3,-,-,-,-,-,-,-,-,-,619,11,25,1,-,-
6,3,Death (Poisoning),81,54,12,15,17,-,-,-,15,9,-,9,-,-,-,-,-,-,-,18,-,-,-,-,-,-,-,-,-,-,65,9,14,4,-,-
7,4,Death (Aggravated Domestic Violence),362,107,24,231,239,15,-,2,214,208,4,73,2,7,1,6,-,-,4,269,3,1,10,-,-,-,-,-,-,-,174,25,138,16,-,-
8,5,Death(Fire Out Breaks),42,25,11,6,14,-,-,-,6,8,2,3,-,-,-,-,-,-,-,13,-,-,-,-,-,-,-,-,-,-,16,24,7,19,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,96,Firearms Act,109,38,23,48,54,17,-,3,28,61,1,2,1,20,-,-,-,-,4,41,17,1,-,-,-,1,-,1,-,"16,000,000",95,-,2,-,-,-
121,97,Enguli Act,4,3,1,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,5,-,-,-,-,-
122,98,UWA Statute,648,112,89,447,485,269,8,26,144,609,7,17,-,377,-,11,-,10,42,193,249,3,4,-,-,107,-,15,10,"172,222,000",608,-,8,-,"26,000,000","26,000,000"
123,99,Local Government Act,4,2,1,1,1,-,-,-,1,1,-,-,-,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,-,4,-,-,-,-,-
124,100,All other Acts,821,345,189,287,430,173,7,19,93,641,12,76,-,323,8,44,-,1,56,297,121,2,3,-,-,120,21,41,60,"69,060,000",710,10,62,9,"241,790,000","440,000"

In [10]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'REPORTED CASES', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'PERFOMANCE', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'PERSONS TAKEN TO COURT', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'SENTENCES IMPOSED BY COURTS', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37'],
      dtype='object')